services:
  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  web:
    image: web
    build:
      context: .
      dockerfile: Web/Dockerfile
